radicle-dev/workstreams-app

src/lib/components/ExploreCard.svelte
src/lib/components/WorkstreamDetail.svelte
src/lib/stores/wallet/wallet.ts
src/lib/stores/workstreams/types.ts

Checks the newly-added `applicants` array on workstreams to decide if the user may apply to a given workstream.

Don't allow applying for already applied-to workstreams

---

package.json
yarn.lock

We merged the design-system export branch into `main` in the Upstream
repo, so that we can use it in any other project. This also pins the
design system to a specific commit, so that accidental upgrades don't
break this UI.

chore: point to the correct git repository

---

src/lib/components/ExploreCard.svelte
src/lib/stores/auth/auth.ts

Calls the new /logout endpoint on the API to explicitly destroy the client's current session when clicking on "Log out", and also changes the condition for the "Apply" button to be enabled to ensure that you can't apply while logged out.

fix: Logout on auth clear & prevent applying to something while logged out

---

src/lib/config.ts

In order to force the prod config (and with that the API URL) to be used during development, create a `.env` file in the project's root directory with the following content: 
```
VITE_USE_PROD_CONFIG=true
```

feat: Allow using prod config with a new .env var

---

src/lib/components/User.svelte
src/lib/stores/ensNames.ts

- Adds a new `ensNames` store which ensures we only resolve each address once per session.
- Resolves avatar URLs (if present) and displays the avatar in place of the blockie.
- Adds a neat little crossfade transition when a name or avatar is resolved, which makes things look a lot less glitchy.
Resolves #33
Resolves #55

feat: Ens Name store, resolve avatars

---

src/lib/components/User.svelte

fix: Avatar spacing if address not shown

---

src/lib/components/ApplicationModal.svelte
src/lib/components/Connect.svelte
src/lib/components/User.svelte
src/lib/components/WorkstreamDetail.svelte
src/lib/components/WorkstreamPageHeader.svelte
src/lib/stores/auth/auth.ts
src/lib/stores/connectedAndLoggedIn.ts
src/lib/stores/ensNames.ts
src/lib/stores/headerContent.ts
src/lib/stores/wallet/wallet.ts
src/routes/__layout.svelte
src/routes/dashboard/index.svelte

Update`walletStore.chainId` when the network changes. Fetch ENS names from the current network and auto-reloads ENS names when the network is updated. Display a warning if the network !== mainnet. No longer crash the application and instead block the login button if no web3 wallet is present.
Resolves #72
Resolves #59

feat: Support Testnet ENS, refactor: Improve wallet store

---

scripts/install-design-system-static-assets.sh
src/app.css

Turns out this works just fine.
You can just delete the `./static/styles` folder locally after this is merged.

Simplify design system CSS imports

---

src/lib/components/User.svelte

There seems to be an issue (?) with SvelteKit that causes it to wait for all `transition` directives on a page to conclude before destroying the component on navigation, which causes both pages to briefly appear on screen during navigation if the previous page had any `out` transitions on it.
This changes the crossfades on the `User` component to only transition `in` and mitigates the problem.
It potentially resolves #84, though I'm not 100% certain. We should keep an eye on it and reopen if necessary.
Additionally, I added a condition to only crossfade the ens name & avatar if we're not on the first render to avoid pop-in immediately after mounted with an already-populated ENS value for the current address in the store.

fix: both pages on screen during navigation

---

src/lib/stores/workstreams/workstreams.ts

We were attempting to parse error messages from the API as JSON, even though they're not guaranteed to be JSON, causing an error during fetch. For example, 404 responses just have a body of `Not found`.

fix: JSON decode error when workstream request fails or returns 404

---

src/lib/components/Header.svelte
src/routes/__layout.svelte

- Aligns the margins to screen edge to be a consistent `1rem` across header and content.
- Adds a bottom margin to `main` so that the bottom of content doesn't meet the bottom screen edge.

fix: Bottom padding on `main`, align margins of header and content

---

src/lib/stores/wallet/wallet.ts

Previously, the wallet store would wait for a wallet to be connected before initialising, which caused an immediate MetaMask popup when visiting the page. This stops that, while still fetching previously-connected accounts on initialisation.

fix: Prevent Metamask "Connect wallet" dialog from blocking page render on first visit

---

src/lib/components/SetUpPaymentModal/SetUpPaymentModal.svelte
src/lib/components/SetUpPaymentModal/steps/ConfirmValues.svelte
src/lib/components/SetUpPaymentModal/steps/SetDaiAllowance.svelte
src/lib/components/SetUpPaymentModal/steps/WaitPromise.svelte
src/lib/components/User.svelte

Adds a new step that appears while we're waiting for a TX (either DAI allowance or setDrips call) in SetUpPaymentFlow.
If any error occurs during the promise, the error is printed on screen and the user can go back in the flow and retry.
Resolves #94

feat: Wait step while waiting for TX in SetUpPaymentFlow

---

src/lib/components/BalanceButton.svelte
src/lib/stores/drips/index.ts

Adds a basic withdraw button in the balance dropdown. If the withdraw-able balance is > 0, clicking it triggers the collect transaction.

Add withdraw button

---

src/lib/components/BalanceButton.svelte
src/lib/components/Header.svelte
src/lib/components/History/EarnedInbetweenDropdown.svelte
src/lib/components/History/HistoryItem.svelte
src/lib/components/ModalLayout.svelte
src/lib/components/Rate.svelte
src/lib/stores/drips/index.ts
src/lib/stores/drips/utils/streamedBetween.ts
src/lib/stores/workstreams/index.ts
src/routes/history/history.ts
src/routes/history/historyItemAggregators/index.ts
src/routes/history/historyItemAggregators/monthStartInbetween.ts
src/routes/history/historyItemAggregators/streamPaused.ts
src/routes/history/historyItemAggregators/streamStart.ts
src/routes/history/historyItemAggregators/streamStartStop.ts
src/routes/history/historyItemAggregators/streamUnpaused.ts
src/routes/history/historyItemAggregators/streamedInbetween.ts
src/routes/history/historyItemAggregators/today.ts
src/routes/history/historyItemAggregators/withdrawal.ts
src/routes/history/index.svelte
src/routes/history/types.ts

Adds the history view, accessible from the `BalanceButton` dropdown, which aggregates all relevant events to the user and creates a chronological history, including exactly how much was earned or streamed when, and the activity of every incoming or outgoing stream.

feat: History view

---

src/lib/components/TopUpSteps/TopUpValues.svelte
src/lib/stores/tick.ts
src/lib/stores/workstreams/index.ts
src/routes/__layout.svelte
src/routes/history/index.svelte

Adds a new `tick` store for registering and unregistering functions that should be ran periodically. This avoids many different intervals being set for the now-many places where we want something to be recalculated once a second. Like this, all places of the UI will update in the exact same moment, rather than staggered based on when their respective interval was set, and we can centrally control the tick rate.

Central tick store

---

package.json
src/lib/stores/drips/index.ts
src/lib/stores/workstreams/index.ts
src/lib/stores/workstreams/types.ts
src/routes/profile/[address].svelte
yarn.lock

Resolves #123
Filters out any fetched active workstreams in `workstreamsStore` and on the profile page if they are not set up on the current network. Effectively, this means the history, dashboard and someone's profile are now displaying only data from the selected network, and users can have both test streams and real streams on the same address at the same time.
Also changes to a multi-network version of the drips sdk, making it possible to create streams on mainnet.

feat: Show only active streams from current chain & support Mainnet

---

src/lib/components/ApplicationModal.svelte
src/lib/components/ApplyModal.svelte
src/lib/components/CreateModal.svelte
src/lib/components/StepperModal/index.svelte
src/lib/components/TopUpSteps/TopUpValues.svelte
src/lib/components/WorkstreamCard/index.svelte
src/lib/components/WorkstreamDetail/ActiveStream.svelte
src/lib/components/WorkstreamDetail/ApplicationList.svelte
src/lib/components/WorkstreamDetail/index.svelte
src/lib/stores/wallet/wallet.ts
src/lib/stores/workstreams/index.ts
src/lib/stores/workstreams/methods/fetchRelevantWorkstreams.ts
src/routes/dashboard/index.svelte
src/routes/history/index.svelte

Ensures reactivity of UI after performing a number of actions.
- Workstreams now immediately appear after creating them using the workstream creation modal.
- Applications now immediately appear on the Workstream Detail View after submitting the Application Create modal.
- The results of on-chain interactions such as pausing, unpausing and topping up a stream now are now immediately visible on the dashboard & workstream detail views.
- Application accept / reject buttons now appear & disappear accordingly when switching between the creator account and an arbitrary other account.
- After accepting or a rejecting an application, the workstream detail view now immediately updates accordingly.
Resolves #142

fix: UI reactivity after API interactions

---

package.json
yarn.lock

This is necessary so that we can archive the https://github.com/radicle-dev/radicle-upstream repository. This also means that we don't necessarily need `yarn` v2 workspaces anymore, `npm` could also do.

Use standalone design system dependency

---

src/routes/index.svelte

Adds a simple empty state to the explore page if no RFA workstreams are returned from the API.

feat: explore page empty state

---

.eslintrc.cjs
src/lib/stores/drips/index.ts

Enables 'no-comment' and 'no-unused-vars' as errors. Will automatically be checked on commit using `lint-staged`.

Enhance linter config

---

src/lib/components/CreateModal.svelte
src/lib/components/SetUpPaymentSteps/steps/ConfirmValues.svelte
src/lib/components/SetUpPaymentSteps/steps/gnosis-safe/ConfirmValues.svelte
src/lib/components/SetUpPaymentSteps/steps/gnosis-safe/WaitingForConfirmation.svelte
src/lib/components/WorkstreamCard.svelte
src/lib/components/WorkstreamDetail/ActiveStream.svelte
src/lib/components/WorkstreamDetail/index.svelte
src/lib/components/WorkstreamStateBadge.svelte
src/lib/stores/drips/index.ts
src/lib/stores/wallet/wallet.ts
src/lib/stores/workstreams/index.ts
src/lib/stores/workstreams/methods/fetchRelevantWorkstreams.ts
src/lib/stores/workstreams/types.ts
src/routes/dashboard/index.svelte
src/routes/history/index.svelte

Depends on https://github.com/radicle-dev/workstreams-api-node/pull/28 and DB migration
This PR removes the `pending` state from Workstreams, and instead infers whether a workstream should be displayed as "Active" or "Pending setup" using on-chain data. As part of that, the workstream activation call has been removed. Additionally, drips account IDs are no longer generated client-side — instead, the server-generated ID on workstream creation is used when calling `setDrips`.
Resolves #166

Remove pending state

---

src/lib/components/BalanceButton.svelte
src/lib/components/WithdrawSteps/Intro.svelte
src/lib/stores/drips/utils/streamedBetween.ts
src/lib/stores/workstreams/index.ts
src/routes/history/historyItemAggregators/monthStartInbetween.ts
src/routes/history/historyItemAggregators/streamedInbetween.ts
src/routes/history/historyItemAggregators/today.ts
src/routes/history/index.svelte

Displays the earnings in the current Drips cycle up in the balance dropdown, and replaces the total earned value in the button label with the more practical value of `currently withdrawable + earned in current cycle`.
Behind the scenes, I also consolidated some of the logic for balance estimation.

feat: Estimate earnings in current cycle

---

src/lib/stores/drips/index.ts

This fixes an issue with pausing and unpausing streams caused by the new simplified `DripHistory` data structure.

fix: pause & unpause not working

---

src/routes/history/historyItemAggregators/streamStartStop.ts

In some situations, the `stream ran out of funds` and `stream topped up` events were missing in the history, this fixes it.

fix: no startstop items in history
