radicle-dev/workstreams-app

- package-lock.json
- package.json
- src/lib/WorkstreamCard.svelte
- src/lib/header/Header.svelte
- src/routes/__layout.svelte
- src/routes/index.svelte
- src/styles/global.css
- src/styles/reset.css
Added in the data model and some first styling.
Signed-off-by: Julien Donck <hello@juliendonck.com>
> first styles + data

- package-lock.json
- package.json
- src/lib/components/WorkstreamCard/index.svelte
- src/lib/components/WorkstreamDetail/index.svelte
- src/lib/shared/Markdown.svelte
- src/lib/stores/workstreamsStore.js
- src/lib/utils/format.ts
- src/routes/[id].svelte
- src/routes/my-workstreams.svelte
- add markdown support
- hyphenate urls
> Improvements

- package-lock.json
- package.json
- src/lib/components/Header/index.svelte
- src/lib/shared/Connect.svelte
This PR adds the `web3-stores` package to provide a Web3Provider to connect over Metamask.
Feel free provide feedback
> Add Web3Providers

- package.json
- src/lib/components/ActionRow.svelte
- src/lib/components/ApplicationModal.svelte
- src/lib/components/Card.svelte
- src/lib/components/ExploreCard.svelte
- src/lib/components/Rate.svelte
- src/lib/components/User.svelte
- src/lib/components/WorkstreamCard.svelte
- src/lib/components/WorkstreamDetail.svelte
- src/lib/config.ts
- src/lib/stores/workstreams/types.ts
- src/lib/utils/format.ts
- src/routes/dashboard/index.svelte
- src/routes/workstream/[id].svelte
- yarn.lock
- adds an application read modal
- improves a bunch of components
- improves the action rows
- builds out applications on workstream detail page
@efstajas I'd like some help with the actions to accept or deny an application. Both on the detail page and in the applicationModal.
> Feature: Build out application front end

- package.json
- src/lib/components/Modal.svelte
- yarn.lock
Uses the latest design system where we fixed elevation theming.
> Use latest design system

- src/lib/config.ts
API moved to europe, so let's update the URL.
> chore: Update api url

- src/lib/config.ts
- src/routes/dashboard/index.svelte
Adds a new section that shows pending workstreams that the current user is assigned to.
> fix: Add "waiting for payment setup" section

- src/lib/stores/workstreams/workstreams.ts
- src/routes/dashboard/index.svelte
- src/routes/index.svelte
Fixes type error while calculating current incoming stream total by ensuring incoming workstreams use BigInt types as their `wei` values.
Resolves #89
> fix type error on dashboard

- src/lib/components/Connect.svelte
- src/routes/__layout.svelte
Signed-off-by: Julien Donck <hello@juliendonck.com>
> moves network indicator to bottom right fixed

- src/lib/components/ApplyModal.svelte
- src/lib/components/TextInput.svelte
Resolves #92 
Also changes the apply modal to use `number` inputs and prevents negative values.
> fix: Applying without changing the total incorrectly proposes a fraction of the original workstream total

- src/lib/components/ModalLayout.svelte
- src/lib/components/WorkstreamCard/ActionRow.svelte
- src/routes/workstream/[id].svelte
> Fix ts warnings

- src/lib/components/BalanceButton.svelte
- src/lib/components/Connect.svelte
- src/lib/components/LoadingDots.svelte
> use LoadingDots component for connect & balance buttons

- src/lib/components/TopUpSteps/TopUpValues.svelte
> Dont show 'runs until' in Top Up Modal while top up amount is zero

- package.json
- src/lib/components/ApplyModal.svelte
- src/lib/components/CreateModal.svelte
- yarn.lock
We changed the `TextArea` API a little. Should look and feel the same.
> Update the design system dependency

- src/lib/components/WorkstreamCard/index.svelte
> fix: Wonky explore page layout

- src/lib/components/ApplyButton.svelte
- src/lib/components/WorkstreamDetail/ApplyRow.svelte
- src/lib/components/WorkstreamDetail/index.svelte
- src/lib/components/WorkstreamPageHeader.svelte
> fix: apply button appears when it shouldn't

- src/lib/components/SetUpPaymentSteps/steps/ConfirmValues.svelte
- src/lib/components/WorkstreamDetail/index.svelte
> fix: Crash in SetupPaymentFlow when clearing top up amount value

- src/lib/components/CreateModal.svelte
- src/lib/components/Modal.svelte
- src/lib/components/TypeSwitcher.svelte
- src/lib/stores/ensNames.ts
- src/lib/stores/workstreams/types.ts
> feat: Allow direct assignment

- src/lib/components/TopUpSteps/TopUpValues.svelte
> feat: validate top up amount against user dai balance

- src/routes/history/historyItemAggregators/streamUnpaused.ts
> fix: unpauses missing in history

- jest.config.cjs
- package.json
- src/lib/components/History/HistoryItem.svelte
- src/lib/stores/__test__/tick.test.ts
- src/lib/stores/tick.ts
- src/routes/history/history.test.ts
- src/routes/history/history.ts
- src/routes/history/historyItemAggregators/__test__/monthStartInbetween.test.ts
- src/routes/history/historyItemAggregators/__test__/streamedInbetween.test.ts
- src/routes/history/historyItemAggregators/monthStartInbetween.ts
- src/routes/history/historyItemAggregators/streamedInbetween.ts
- src/routes/history/historyItemAggregators/today.ts
- yarn.lock
Adds tests for
- Tick store
- History store logic
- "MonthStartInbetween" history aggregator function
- "StreamedInbetween" history aggregator function
> add a few quick tests
